import '~/styles/globals.css'

import { type Metadata } from 'next'
import { Geist } from 'next/font/google'
import { NuqsAdapter } from 'nuqs/adapters/next/app'
import { ThemeProvider } from '~/providers/theme-provider'
import { Toaster } from '~/components/ui/sonner'

export const metadata: Metadata = {
    title: 'Create T3 App',
    description: 'Generated by create-t3-app',
    icons: [{ rel: 'icon', url: '/favicon.ico' }],
}

const geist = Geist({
    subsets: ['latin'],
    variable: '--font-geist-sans',
})

export default function RootLayout({
    children,
}: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang='en' className={`${geist.variable}`}>
            <body>
                <ThemeProvider
                    attribute='class'
                    defaultTheme='system'
                    enableSystem
                    disableTransitionOnChange
                >
                    <NuqsAdapter>{children}</NuqsAdapter>
                    <Toaster
                        richColors
                        position='top-right'
                        toastOptions={{ duration: 4000 }}
                    />
                </ThemeProvider>
            </body>
        </html>
    )
}
